### ISSUE TITLE
Showing confirm Terms of Use and cannot press confirm

### ISSUE THREAD

**Issue by Stoffe** [AITGmbH/AIT.VotingExtension#86] opened 2020-04-15 15:44 UTC
No matter if you press Confirm for the terms of use, you cannot go on.
If you press Decline, you cannot use the software.
So this voting addon for Azure DevOps is useless unless you fix this.
- This should maybe be accepted on a project level instead?

**Comment by BarbaraGoeller-AIT** [comment] 2020-05-08 05:12
Hi,

Sorry for the late answer. Due to the current situation caused by the coronavirus we will not take care of the issue immediately but follow up at a later point in time. 
In the meantime you could check if you use the supported browser Chrome. If the problem occurs within Chrome please provide us some further details about the scenario (such as Chrome version, process template of the team project, ...) so that we can investigate issue later on.

Best regards
Barbara

**Comment by Stoffe** [comment] 2020-05-08 07:04
ok, sure, Im using Chrome version 81.0.4044.138 (Official Version) (64-bit)
Latest version as of this writing.

And no, this issue persists... :/
Iven in multiple different organisations so its most likely something with the addon I would say.

**Comment by GeertLommers** [comment] 2020-09-21 07:40
Same problem here with Versie 85.0.4183.102 (Officiële build) (64-bits),

**Comment by marckraak** [comment] 2020-10-15 07:56
Same here: Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by fabiostawinski** [comment] 2020-10-29 07:51
Same here, for all users.

**Comment by Moutasema** [comment] 2020-11-11 11:59
Same here  with both Chrome and Edge latest versions 
Chrome: Version 86.0.4240.183 (Official Build) (64-bit)
Edge: Version 88.0.692.0 (Official build) dev (64-bit)

**Comment by Nickperf** [comment] 2020-11-12 16:24
Same behavior with Chrome and Edge based on Chromium engine. This is becoming a road block now.

**Comment by napatowa** [comment] 2020-12-10 05:02
Has this fix been built and pushed into the marketplace?

**Comment by barbara-goeller** [comment] 2021-01-15 08:11
Hi everybody,

Finally a fix has been released for this issues. Sorry again for the very long waiting time.

Best regards
Barbara

**Closed by barbara-goeller** 2021-01-15 08:11 UTC
