### ISSUE TITLE
Query based voting - Missing Queries

### ISSUE THREAD

**Issue by tparis0022** [AITGmbH/AIT.VotingExtension#63] opened 2019-06-26 12:40 UTC
So I've created a new query to enable users to vote on.
The query has been saved to a Shared Folder directory
When I am configuring the vote settings, the query is not listed in the drop down list.

So! I see an existing completely different query in the drop down list,
I configure the vote to that query and save it.
It works!
So I edit that query and merely save it with it's original name
I go back to the vote settings to look at the voting and it's blank
I visit the vote settings to check the configuration with that query
But the query is now missing from the list too.

I've tried clearing my browser cache, different browsers, different computers.. The queries are not appearing any time fast.

**Comment by BarbaraGoeller-AIT** [comment] 2019-10-17 09:44
Hi,

Sorry for the very late answer. Unfortunately I cannot reproduce any of the described issues. Please be aware that the extension is only supported in Chrome as stated in the [Marketplace Extension description](https://marketplace.visualstudio.com/items?itemName=AITGmbH.asap-voting-aitgmb-de-production).
Could you please try to reproduce the issues in chrome and give me futher details about the scenario (such as Chrome version, process template of the team project, ...).

Best regards
Barbara

**Comment by florianbader** [comment] 2019-11-24 17:10
I couldn't reproduce the issue. I'm closing this for now. If the issue still occurs, please provide more information (browser version, process template [CMMI, Scrum, ...], Azure DevOps version, ...) and reopen the issue.

**Closed by florianbader** 2019-11-24 17:10 UTC
